name: Build and push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_REPOSITORY: weseek/mongodb-awesome-backup

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: v0.3.1

      - name: Login to Docker Hub
        run: >
          echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} |
          docker login --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push latest Docker Image
        run: >
          docker buildx build
          --tag ${DOCKERHUB_REPOSITORY}
          --platform linux/amd64
          --cache-from type=registry,ref=${DOCKERHUB_REPOSITORY}
          --cache-to type=inline
          --push
          .

  publish_description:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - uses: actions/checkout@v2

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          readme-filepath: ./README.md
